#!/bin/bash
# This is a Bash script to run main.m from the command line, in the
# background using Matlab. Pass the fully qualified filename of an
# input file or several input files as arguments. If -p is passed, 
# the run will be parallelized.
#
# Timothy Crone (tjcrone@gmail.com)

# parse arguments
parallel=0
numFiles=1
while [[ $# > 0 ]]; do
  key="$1"
  case $key in
    -v|--version) # show version and exit
    echo "multiporo v0.1.0dev"
    exit
    ;;
    -p|--parallel) # set parallel flag
    parallel=1
    ;;
    *) # anything else is considered an input file
    fileList[numFiles]=$key
    numFiles=$((numFiles+1))
    ;;
  esac
  shift
done
numFiles=$((numFiles-1))

# check number of files
if [[ $numFiles -lt 1 ]]; then
  echo "Error: at least one valid input file must be passed as an argument."
  exit 1
fi

# check input files
for i in $(seq 1 $numFiles); do
  infile=${fileList[$i]}
  if [[ ! -s $infile ]]; then
    echo "Error: $infile is not a valid input file."
    exit 1
  fi
done

# run input files
for i in $(seq 1 $numFiles); do
  infile=${fileList[$i]}
  #echo $infile

  # create log file and temporary run file
  logfile="${infile%_*}_out.log"
  tmpfile=`mktemp $infile.XXXXXX`

  # populate temporary file
  echo "main('$infile');" > $tmpfile

  # run matlab in background in parallel or sequentially
  EXE=`which matlab`
  nohup $EXE -nodesktop -nosplash < $tmpfile > $logfile 2>&1 &
  if [[ parallel -eq "0" ]]; then
    wait
  fi

  # delete temporary file
  rm $tmpfile
done
