function [] = readinput(filename)

% define list of known parameters
knownparameters = { ...
'steady', ...
'adaptivetime', ...
'nstep', ...
'nx', ...
'nz', ...
'd', ...
'Thot', ...
'Tcold', ...
'zreset', ...
'teststring', ...
'kon', ...
'koff'};

% read entire input file
fid = fopen(filename);
s = textscan(fid, '%s%s', 'CommentStyle', '%', 'Delimiter', {'=', ' ', '\t'}, ...
  'MultipleDelimsAsOne', 1);
fclose(fid);

% loop through list of known parameters and assign them to the caller's workspace
for i = 1:length(knownparameters)
  % get index of the current known parameter
  idx = strcmp(knownparameters{i},s{1});

  % check if the parameter value is a number (NaNs cannot be parameter values yet)
  value = str2double(cell2mat(s{2}(idx)));

  % assign parameter value as number or a string
  if ~isnan(value)
    assignin('caller',knownparameters{i}, value);
  else
    assignin('caller',knownparameters{i}, cell2mat(strrep(s{2}(idx),'''','')));
  end
end
